micronaut:
  application:
    name: messageBroker
  server:
    port: 8083
    context-path: message-broker
netty:
  default:
    allocator:
      max-order: 3

telegram:
  token: ${TELEGRAM_BOT_TOKEN}

rabbitmq:
  uri: amqp://localhost:5672
  username: admin
  password: admin
