micronaut:
  application:
    name: messageBroker
  server:
    port: 8083
netty:
  default:
    allocator:
      max-order: 3

rabbitmq:
  uri: amqp://localhost:5672
  username: admin
  password: admin
