version: '3.8'
services:
  reverse-proxy:
    image: "jwilder/nginx-proxy:latest"
    container_name: "reverse-proxy"
    volumes:
        - "html:/usr/share/nginx/html"
        - "dhparam:/etc/nginx/dhparam"
        - "vhost:/etc/nginx/vhost.d"
        - "certs:/etc/nginx/certs"
        - "/run/docker.sock:/tmp/docker.sock:ro"
    restart: "always"
    networks: 
        - "bot-net"
    ports:
        - "80:80"
        - "443:443" 
  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
    container_name: "letsencrypt-helper"
    volumes:
        - "html:/usr/share/nginx/html"
        - "dhparam:/etc/nginx/dhparam"
        - "vhost:/etc/nginx/vhost.d"
        - "certs:/etc/nginx/certs"
        - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
        NGINX_PROXY_CONTAINER: "reverse-proxy"
        DEFAULT_EMAIL: ${EMAIL}
    restart: "always"
    depends_on:
        - "reverse-proxy"
    networks: 
        - "bot-net"
       
  rabbitmq:
    image: rabbitmq:3.8.22-management-alpine
    container_name: rabbitmq
    restart: always
    networks:
        - rabbitmq-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
  
  message-broker:
    image: 4etell/message-broker:0.0.1
    deploy:
        replicas: ${MESSAGE_BROKER_REPLICAS}
    restart: always
    networks:
        - rabbitmq-net
        - bot-net
    environment:
        TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        RABBITMQ_URI: amqp://rabbitmq:5672
        VIRTUAL_HOST: ${APP_DOMAIN}
        LETSENCRYPT_HOST: ${APP_DOMAIN}
        VIRTUAL_PATH: /message-broker
        VIRTUAL_PORT: 8083
    depends_on:
      rabbitmq:
        condition: service_healthy  
        
  message-handler:
    image: 4etell/message-handler:0.0.1
    restart: always
    deploy:
        replicas: ${MESSAGE_HANDLER_REPLICAS}
    networks:
        - rabbitmq-net
    environment:
        CONFIG_SERVICE_URL: http://config-service:8089/config-service
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        CONFIG_SERVICE_USERNAME: ${CONFIG_SERVICE_USERNAME}
        CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
        RABBITMQ_URI: amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy   
        
  config-service:
    image: 4etell/config-service:0.0.1
    container_name: config-service
    restart: always
    networks:
        - rabbitmq-net
        - bot-net
        - minio-net
    environment:
        BASIC_AUTH_USERNAME: ${CONFIG_SERVICE_USERNAME}
        BASIC_AUTH_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
        MINIO_ACCESS_KEY: ${MINIO_USER}
        MINIO_SECRET_KEY: ${MINIO_PASSWORD}
        MINIO_URI: http://minio:9000
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        RABBITMQ_URI: amqp://rabbitmq:5672
        VIRTUAL_PATH: /config-service/admin
        VIRTUAL_HOST: ${APP_DOMAIN}
        LETSENCRYPT_HOST: ${APP_DOMAIN}
        VIRTUAL_PORT: 8089
    depends_on:
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    networks:
        - minio-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BROWSER: "on"
    volumes:
      - ./minio-data:/data
      - ./minio-config:/root/.minio
    command: server /data --console-address ":9005"

networks:
    bot-net:
        external: true
    rabbitmq-net:
        driver: bridge
    minio-net:
        driver: bridge

volumes:
  certs:
  html:
  vhost:
  dhparam:
