micronaut:
  server:
    port: ${REPLICA_NAME}
  application:
    name: messageHandler
netty:
  default:
    allocator:
      max-order: 3

rabbitmq:
  uri: amqp://localhost:5672
  username: admin
  password: admin

config-service:
  queue-name: bot-config-${REPLICA_NAME}
  client-url: ${CONFIG_SERVICE_URL}
