micronaut:
  server:
    port: 8081
  application:
    name: messageHandler
netty:
  default:
    allocator:
      max-order: 3

rabbitmq:
  uri: amqp://localhost:5672
  username: admin
  password: admin
