rabbitmq:
  uri: ${RABBITMQ_URI}
  username: ${RABBITMQ_USER}
  password: ${RABBITMQ_PASSWORD}
minio:
  endpoint: ${MINIO_URI}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: test-bucket-ui2
  flow-file-name: flow.yml