micronaut:
  application:
    name: configService
  server:
    port: 8089
netty:
  default:
    allocator:
      max-order: 3
rabbitmq:
  uri: amqp://localhost:5672
  username: admin
  password: admin